### ISSUE TITLE
Update stable version in repo from 0.0.5 to 0.0.6

### ISSUE THREAD

**Issue by GermanBluefox** [AWhiteKnight/ioBroker.letrika_comgw#15]
# Think about update stable version to 0.0.6
**Version**: stable=**0.0.5** (530 days old) => latest=**0.0.6** (15 days old)
**Installs**: stable=**4** (50%), latest=**1** (12.5%), total=**8**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L847)

**Comment by AWhiteKnight** [comment]
done

**Comment by AWhiteKnight** [comment]
done
